### ISSUE TITLE
Is there any discussion about this repo?

### ISSUE THREAD

**Issue by junfx** [citusdata/pgmasq#1]
Could you provide details about why this repo was abandoned, please?

**Comment by marcocitus** [comment]
One of the fundamental limitations of the approach taken in pgmasq (propagating writes via planner/executor/utility hooks) is that DDL commands have to be propagated to the primary, but then the parser would fail on the standby for the remainder of the transaction. Since the parser runs before any hook, there is no workaround at the moment.
